# GENERATED FROM mineflayer/index.d.ts — DO NOT EDIT MANUALLY.
# Regenerate via: uv run python scripts/generate_stubs.py
"""Optional class-based event handler base.

Subclass :class:`BotHandlers`, override the ``on_<event>`` methods
you care about, then wire the instance via ``bot.bind(handlers)``.

IDEs read the typed signatures from ``bot.pyi`` so 'Override
methods' auto-fill gives you the correct parameter list and types.
"""

from __future__ import annotations

__all__ = ["BotHandlers"]


class BotHandlers:
    """Base class for class-based event handlers."""

    def on_action_bar(self, *_args: object, **_kwargs: object) -> None: ...
    def on_block_break_progress_end(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_block_break_progress_observed(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_block_update(self, *_args: object, **_kwargs: object) -> None: ...
    def on_block_update_x_y_z(self, *_args: object, **_kwargs: object) -> None: ...
    def on_boss_bar_created(self, *_args: object, **_kwargs: object) -> None: ...
    def on_boss_bar_deleted(self, *_args: object, **_kwargs: object) -> None: ...
    def on_boss_bar_updated(self, *_args: object, **_kwargs: object) -> None: ...
    def on_breath(self, *_args: object, **_kwargs: object) -> None: ...
    def on_chat(self, *_args: object, **_kwargs: object) -> None: ...
    def on_chest_lid_move(self, *_args: object, **_kwargs: object) -> None: ...
    def on_chunk_column_load(self, *_args: object, **_kwargs: object) -> None: ...
    def on_chunk_column_unload(self, *_args: object, **_kwargs: object) -> None: ...
    def on_death(self, *_args: object, **_kwargs: object) -> None: ...
    def on_digging_aborted(self, *_args: object, **_kwargs: object) -> None: ...
    def on_digging_completed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_dismount(self, *_args: object, **_kwargs: object) -> None: ...
    def on_end(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_attach(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_attributes(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_critical_effect(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_crouch(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_dead(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_detach(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_eat(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_eating_grass(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_effect(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_effect_end(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_elytra_flew(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_equip(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_gone(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_hand_swap(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_hurt(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_magic_critical_effect(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_entity_moved(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_shaking_off_water(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_entity_sleep(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_spawn(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_swing_arm(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_tamed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_taming(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_uncrouch(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_update(self, *_args: object, **_kwargs: object) -> None: ...
    def on_entity_wake(self, *_args: object, **_kwargs: object) -> None: ...
    def on_error(self, *_args: object, **_kwargs: object) -> None: ...
    def on_experience(self, *_args: object, **_kwargs: object) -> None: ...
    def on_forced_move(self, *_args: object, **_kwargs: object) -> None: ...
    def on_game(self, *_args: object, **_kwargs: object) -> None: ...
    def on_goal_reached(self, *_args: object, **_kwargs: object) -> None: ...
    def on_goal_updated(self, *_args: object, **_kwargs: object) -> None: ...
    def on_hardcoded_sound_effect_heard(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_health(self, *_args: object, **_kwargs: object) -> None: ...
    def on_inject_allowed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_item_drop(self, *_args: object, **_kwargs: object) -> None: ...
    def on_kicked(self, *_args: object, **_kwargs: object) -> None: ...
    def on_login(self, *_args: object, **_kwargs: object) -> None: ...
    def on_message(self, *_args: object, **_kwargs: object) -> None: ...
    def on_messagestr(self, *_args: object, **_kwargs: object) -> None: ...
    def on_mount(self, *_args: object, **_kwargs: object) -> None: ...
    def on_move(self, *_args: object, **_kwargs: object) -> None: ...
    def on_note_heard(self, *_args: object, **_kwargs: object) -> None: ...
    def on_particle(self, *_args: object, **_kwargs: object) -> None: ...
    def on_path_reset(self, *_args: object, **_kwargs: object) -> None: ...
    def on_path_stop(self, *_args: object, **_kwargs: object) -> None: ...
    def on_path_update(self, *_args: object, **_kwargs: object) -> None: ...
    def on_physic_tick(self, *_args: object, **_kwargs: object) -> None: ...
    def on_physics_tick(self, *_args: object, **_kwargs: object) -> None: ...
    def on_piston_move(self, *_args: object, **_kwargs: object) -> None: ...
    def on_player_collect(self, *_args: object, **_kwargs: object) -> None: ...
    def on_player_joined(self, *_args: object, **_kwargs: object) -> None: ...
    def on_player_left(self, *_args: object, **_kwargs: object) -> None: ...
    def on_player_updated(self, *_args: object, **_kwargs: object) -> None: ...
    def on_rain(self, *_args: object, **_kwargs: object) -> None: ...
    def on_resource_pack(self, *_args: object, **_kwargs: object) -> None: ...
    def on_respawn(self, *_args: object, **_kwargs: object) -> None: ...
    def on_score_removed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_score_updated(self, *_args: object, **_kwargs: object) -> None: ...
    def on_scoreboard_created(self, *_args: object, **_kwargs: object) -> None: ...
    def on_scoreboard_deleted(self, *_args: object, **_kwargs: object) -> None: ...
    def on_scoreboard_position(self, *_args: object, **_kwargs: object) -> None: ...
    def on_scoreboard_title_changed(
        self, *_args: object, **_kwargs: object
    ) -> None: ...
    def on_sleep(self, *_args: object, **_kwargs: object) -> None: ...
    def on_sound_effect_heard(self, *_args: object, **_kwargs: object) -> None: ...
    def on_spawn(self, *_args: object, **_kwargs: object) -> None: ...
    def on_spawn_reset(self, *_args: object, **_kwargs: object) -> None: ...
    def on_team_created(self, *_args: object, **_kwargs: object) -> None: ...
    def on_team_member_added(self, *_args: object, **_kwargs: object) -> None: ...
    def on_team_member_removed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_team_removed(self, *_args: object, **_kwargs: object) -> None: ...
    def on_team_updated(self, *_args: object, **_kwargs: object) -> None: ...
    def on_time(self, *_args: object, **_kwargs: object) -> None: ...
    def on_title(self, *_args: object, **_kwargs: object) -> None: ...
    def on_unmatched_message(self, *_args: object, **_kwargs: object) -> None: ...
    def on_used_firework(self, *_args: object, **_kwargs: object) -> None: ...
    def on_wake(self, *_args: object, **_kwargs: object) -> None: ...
    def on_whisper(self, *_args: object, **_kwargs: object) -> None: ...
    def on_window_close(self, *_args: object, **_kwargs: object) -> None: ...
    def on_window_open(self, *_args: object, **_kwargs: object) -> None: ...
