# GENERATED FROM bot.pyi — DO NOT EDIT MANUALLY.
# Regenerate via: uv run python scripts/generate_stubs.py
"""Every attribute name `Bot` really has, for did-you-mean on a typo.

`Bot.__getattr__` forwards unknown names to the JS proxy, and JSPyBridge answers
`None` for a property JavaScript does not have rather than raising — so a
misspelling used to evaluate to `None` in silence (`bot.usernam`) or fail as
`'NoneType' object is not callable` (`bot.move_foward(3)`), naming nothing.

Deciding "is this a typo?" needs the set of real names, and the runtime cannot
supply it: `list(bot_proxy)` returns only JavaScript's *own* enumerable keys, so
a documented property that has not been assigned yet is missing from it —
`bot.vehicle` is `undefined` until the first mount, and treating it as a typo
would break working scripts. `bot.pyi` is generated from mineflayer's own
`index.d.ts` and does have the full surface, so it is the source of truth here.
"""

from __future__ import annotations

BOT_MEMBERS: frozenset[str] = frozenset(
    {
        "__init__",
        "acceptResourcePack",
        "action",
        "activateBlock",
        "activateEntity",
        "activateEntityAt",
        "activateItem",
        "addChatPattern",
        "addChatPatternSet",
        "attack",
        "awaitMessage",
        "bind",
        "blockAt",
        "blockAtCursor",
        "blockAtEntityCursor",
        "blockInSight",
        "canDigBlock",
        "canSeeBlock",
        "chat",
        "chatAddPattern",
        "chatPatterns",
        "clearControlStates",
        "clickWindow",
        "closeWindow",
        "connect",
        "consume",
        "controlState",
        "craft",
        "creative",
        "currentWindow",
        "deactivateItem",
        "denyResourcePack",
        "dig",
        "digTime",
        "dismount",
        "drop",
        "elytraFly",
        "end",
        "entities",
        "entity",
        "entityAtCursor",
        "equip",
        "experience",
        "findBlock",
        "findBlocks",
        "find_block",
        "find_blocks",
        "fireworkRocketDuration",
        "fish",
        "food",
        "foodSaturation",
        "game",
        "getControlState",
        "getEquipmentDestSlot",
        "getExplosionDamages",
        "get_block",
        "get_block_property",
        "get_front_block",
        "get_hand",
        "get_height",
        "get_pitch",
        "get_player_pos",
        "get_pos",
        "get_sneak",
        "get_x",
        "get_y",
        "get_yaw",
        "get_z",
        "hasPlugin",
        "health",
        "heldItem",
        "hold",
        "inventory",
        "isABed",
        "isRaining",
        "isSleeping",
        "is_riding",
        "jump",
        "loadPlugin",
        "loadPlugins",
        "load_plugin",
        "look",
        "lookAt",
        "look_at",
        "look_block",
        "look_level",
        "majorVersion",
        "mount",
        "moveSlotItem",
        "moveVehicle",
        "move_backward",
        "move_forward",
        "move_left",
        "move_right",
        "nearestEntity",
        "openAnvil",
        "openBlock",
        "openChest",
        "openContainer",
        "openDispenser",
        "openEnchantmentTable",
        "openEntity",
        "openFurnace",
        "openVillager",
        "oxygenLevel",
        "pathfinder",
        "physics",
        "physicsEnabled",
        "place",
        "placeBlock",
        "placeEntity",
        "player",
        "players",
        "protocolVersion",
        "putAway",
        "putSelectedItemRange",
        "quickBarSlot",
        "quit",
        "recipesAll",
        "recipesFor",
        "registry",
        "removeChatPattern",
        "require",
        "respawn",
        "run_forever",
        "scoreboard",
        "scoreboards",
        "setCommandBlock",
        "setControlState",
        "setQuickBarSlot",
        "setSettings",
        "set_height",
        "set_turn",
        "settings",
        "simpleClick",
        "sleep",
        "sneak",
        "spawnPoint",
        "stopDigging",
        "supportFeature",
        "swingArm",
        "tabComplete",
        "tablist",
        "targetDigBlock",
        "teamMap",
        "teams",
        "thunderState",
        "time",
        "toss",
        "tossStack",
        "trade",
        "transfer",
        "turn",
        "turn_left",
        "turn_right",
        "unequip",
        "unhold",
        "updateHeldItem",
        "updateSign",
        "use",
        "useOn",
        "use_player",
        "username",
        "usingHeldItem",
        "vehicle",
        "version",
        "wait",
        "waitForChunksToLoad",
        "waitForTicks",
        "wait_spawn",
        "wake",
        "whisper",
        "world",
        "writeBook",
    }
)

__all__ = ["BOT_MEMBERS"]
